#!/bin/bash

# Usage: gufo serve llm [OPTIONS]
# 
# Start the OpenAI/Anthropic-compatible text LLM HTTP server.
# 
# Model:
  # -m, --model <PATH>         Path to GGUF model file (default: models/Qwen3.5-4B-BF16.gguf)
      # --mmproj <PATH>        Qwen BF16 vision sidecar (auto-discovered beside model)
      # --served-model-name <ID> Model identifier exposed by the OpenAI API
  # -c, --context <N>          Maximum context tokens (default: 4096)
  # 
# Sampling Defaults:
  # -n, --max-tokens <N>       Default maximum new tokens per response (default: 128)
  # -t, --temperature <T>      Randomness scale; 0.0 selects greedy argmax (default: 0.0)
      # --top-k <K>            Keep only the K highest-logit tokens (default: 0 = disabled)
      # --top-p <P>            Keep the smallest token set whose cumulative probability reaches P (default: 1.0 = disabled)
      # --min-p <P>            Keep tokens with probability at least P times the best token (default: 0.0 = disabled)
      # --min-keep <N>         Minimum candidates retained by enabled sampling filters (default: 0)
  # -s, --seed <N>             RNG seed for reproducible generation (default: -1 = random)
      # --repeat-penalty <N>   Multiplicative penalty for recently used tokens (default: 1.0 = disabled)
      # --repeat-last-n <N>    Trailing token window used by repetition penalties (default: 64; 0 = disabled)
      # --frequency-penalty <N> Penalty multiplied by each token's generated occurrence count (default: 0.0 = disabled)
      # --presence-penalty <N> One-time penalty for tokens already generated in this response (default: 0.0 = disabled)
      # 
# Reasoning Defaults:
      # --think <MODE>         Default reasoning mode: on, off, or auto (default: model template)
      # --reasoning-effort <LEVEL> Default effort: auto, minimal, low, medium, high, xhigh, or max
      # --preserve-thinking <MODE> Replay prior reasoning: on, off, or auto
      # 
# Speculative:
      # --speculative <MODE>   HTTP draft backend: dspark, dflash2, mtp, or off
      # --dflash-model <PATH>  Path to Qwen DFlash2 GGUF file
      # --draft-policy <POLICY> DFlash2 block length: fixed or adaptive (default: adaptive)
      # --dspark-model <PATH>  Path to DeepSeek V4 Flash DSpark support GGUF file
      # --mtp-model <PATH>     Path to the Qwen MTP draft GGUF (Qwen3.8-Flash-Next: the mtp-...-shared-*.gguf sidecar)
  # -d, --draft-tokens <N>     Maximum speculative draft tokens evaluated per step (default: 7)
      # --min-draft-tokens <N> Adaptive draft floor (default: 1)
      # 
# Scheduling:
      # --prefill-chunk <N>    Maximum prompt tokens between active decode rounds (default: 512)
      # --max-pending <N>      Maximum queued generation requests (default: 16)
      # --max-pending-per-client <N> Maximum queued requests per client IP (default: 4)
      # --request-timeout-ms <MS> Queue plus generation timeout; 0 disables it (default: 0)
      # --max-output-bytes <N> Maximum generated bytes per request (default: 1048576)
      # --max-buffered-output-bytes <N> Maximum queued stream bytes per request (default: 65536)
      # --max-buffered-output-total <N> Maximum queued stream bytes across requests (default: 262144)
      # 
# Cache:
      # --cache-disk <DIR>     Opt-in restart-safe continuation cache directory
      # --cache-disk-bytes <N> Total retained disk-cache byte budget (default: 4294967296)
      # --cache-disk-staging-bytes <N> Single-operation RAM staging byte limit (default: 536870912)
      # 
# Server:
  # -i, --host <IP>            Bind address
  # -p, --port <N>             Port to listen on
  # -j, --sessions <N>         Preallocated GPU request sessions
      # --max-connections <N>  Maximum simultaneous HTTP connections
      # --max-request-bytes <N> Maximum HTTP request body bytes
      # --api-key <KEY>        API key
      # 
# General:
  # -v, --verbose              Verbose logging
  # -h, --help                 Print help
#   

export HIP_PATH=/opt/rocm
export ROCM_PATH=/opt/rocm
export HIP_PLATFORM=amd
export HIP_CLANG_PATH=/opt/rocm/llvm/bin
export HIP_INCLUDE_PATH=/opt/rocm/include
export HIP_LIB_PATH=/opt/rocm/lib
export HIP_DEVICE_LIB_PATH=/opt/rocm/lib/llvm/amdgcn/bitcode
export PATH=/opt/rocm/bin:/opt/rocm/llvm/bin:$PATH
export LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/lib64:/opt/rocm/llvm/lib:${LD_LIBRARY_PATH:-}
export LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/lib64:${LIBRARY_PATH:-}
export CPATH=/opt/rocm/include:${CPATH:-}
export PKG_CONFIG_PATH=/opt/rocm/lib/pkgconfig:${PKG_CONFIG_PATH:-}


MODEL="/home/praburaja/projects/llm/models/gguf/Qwen3.8-Flash-Next/Q4_K_XL/Qwen3.8-Flash-Next-UD-Q4_K_XL-00001-of-00004.gguf"
MMPROJ="/home/praburaja/projects/llm/models/gguf/Qwen3.8-Flash-Next/mmproj-BF16.gguf"
MTP="/home/praburaja/projects/llm/models/gguf/Qwen3.8-Flash-Next/mtp-Qwen3.8-Flash-Next-Q8_0_unsloth.gguf"
build_rocm10/gufo serve llm -v -i "0.0.0.0" -p 8083 -c 131072 -n 32768 --model "$MODEL" --mmproj "$MMPROJ" --speculative mtp --mtp-model "$MTP" --sessions 2 --think on --reasoning-effort xhigh
