#!/usr/bin/env python3
"""Compile the retained gfx1151 H3 attention kernel into a C++ header."""

from __future__ import annotations

import argparse
import math
import os
import re
from pathlib import Path

os.environ.setdefault("TRITON_F32_DEFAULT", "ieee")

from triton.backends.compiler import GPUTarget
from triton.compiler import ASTSource, compile

from h3_attention_kernel import h3_attention_forward


def metadata_value(assembly: str, name: str) -> int:
    match = re.search(rf"^\s*\.{name}:\s+(\d+)$", assembly, re.MULTILINE)
    if match is None:
        raise RuntimeError(f"missing {name} in AMDGPU kernel metadata")
    return int(match.group(1))


def render_header(code: bytes, shared_bytes: int) -> str:
    rows = []
    for offset in range(0, len(code), 12):
        values = ", ".join(f"0x{value:02x}" for value in code[offset : offset + 12])
        rows.append(f"    {values},")
    payload = "\n".join(rows)
    return f"""// Generated by tools/gufo/compile_h3_attention.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace gufo::minimax_h3::generated {{

inline constexpr std::uint32_t kH3AttentionBlockM = 64;
inline constexpr std::uint32_t kH3AttentionThreads = 128;
inline constexpr std::uint32_t kH3AttentionSharedBytes = {shared_bytes};
inline constexpr std::array<std::uint8_t, {len(code)}> kH3AttentionCode = {{
{payload}
}};

}}  // namespace gufo::minimax_h3::generated
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    source = ASTSource(
        h3_attention_forward,
        {
            "query": "*bf16",
            "key": "*bf16",
            "value": "*bf16",
            "output": "*bf16",
            "sequence": "i32",
        },
        {
            "OUTPUT_HEAD_STRIDE": 56 * 128,
            "QK_SCALE": math.log2(math.e) / math.sqrt(128.0),
            "BLOCK_M": 64,
            "BLOCK_N": 32,
            "HEAD_DIM": 128,
        },
        {
            (index,): [
                ["tt.divisibility", 16],
                ["tt.pointer_range", 32],
            ]
            for index in range(4)
        },
    )
    compiled = compile(
        source,
        target=GPUTarget("hip", "gfx1151", 32),
        options={
            "num_warps": 4,
            "num_stages": 1,
            "waves_per_eu": 0,
            "matrix_instr_nonkdim": 0,
            "kpack": 1,
            "schedule_hint": "attention",
            # All offsets for the admitted 37,716-row shape fit in signed i32.
            # Removing generic overflow instrumentation is what keeps this
            # exact-shape kernel spill-free on gfx1151.
            "sanitize_overflow": False,
        },
    )
    assembly = compiled.asm["amdgcn"]
    vgpr_spills = metadata_value(assembly, "vgpr_spill_count")
    sgpr_spills = metadata_value(assembly, "sgpr_spill_count")
    private_bytes = metadata_value(assembly, "private_segment_fixed_size")
    shared_bytes = int(compiled.metadata.shared)
    if vgpr_spills != 0 or sgpr_spills != 0 or private_bytes != 0:
        raise RuntimeError(
            "retained gfx1151 attention kernel spilled: "
            f"vgpr={vgpr_spills}, sgpr={sgpr_spills}, private={private_bytes}"
        )
    if shared_bytes != 24_576:
        raise RuntimeError(
            f"unexpected gfx1151 attention LDS requirement: {shared_bytes}"
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_header(compiled.asm["hsaco"], shared_bytes),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
