#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <limits>
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "src/core/crypto/sha256.hpp"
#include "src/models/deepseek_v4_flash/engine.hpp"

namespace gufo::testing::ds4 {
void CheckTokenGoldens(const models::deepseek_v4_flash::Model& model);
void ScoreOfficialReference(
    const std::shared_ptr<models::deepseek_v4_flash::Model>& model,
    const std::string& output_path);
void DumpReferenceFrontiers(
    const std::shared_ptr<models::deepseek_v4_flash::Model>& model,
    const std::string& output_directory, bool prefill_only);
}  // namespace gufo::testing::ds4

namespace {

void Expect(bool condition, const char* message) {
  if (!condition) {
    std::cerr << "FAIL: " << message << '\n';
    std::exit(EXIT_FAILURE);
  }
}

void Expect(bool condition, const std::string& message) {
  Expect(condition, message.c_str());
}

constexpr std::string_view kTrajectoryPrompt =
    "Continue this technical explanation with concrete examples and "
    "tradeoffs: Virtual memory lets an operating system";

// Generated by antirez/ds4 revision 84cc882352757baf628a1776badf7cc54d584e28.
constexpr std::array<int, 128> kPinnedDs4Trajectory{
    1347,  17491, 305,  11586, 8412,  412,  260,  1840,  6464,  14261, 16,
    983,   18954, 6781, 294,   1192,  1949, 6464, 436,   6623,  343,   458,
    1205,  436,   344,  1505,  362,   11,   5566, 6460,  305,   17491, 11096,
    16,    983,   4491, 6464,  19627, 3510, 304,  6783,  16,    983,   4491,
    270,   1487,  850,  10920, 16,    1890, 436,  28162, 260,   1699,  1347,
    850,   6464,  1099, 344,   22920, 3510, 16,   455,   1840,  41036, 477,
    28,    7294,  469,  850,   4190,  6783, 29,   15842, 4256,  1014,  29,
    305,   3283,  362,  1487,  31489, 3504, 304,  5167,  18585, 4346,  91604,
    16,    983,   588,  990,   1635,  260,  1487, 39376, 16,    983,   6026,
    25454, 1014,  304,  10181, 6464,  16,   983,  6026,  1014,  304,   30376,
    16,    983,   9347, 270,   15599, 294,  270,  20616, 14,    2918,  436,
    2231,  366,   9026, 295,   6464,  9694, 436,
};

void CheckPinnedTrajectory(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  std::string error;
  const auto prompt = model->Tokenize(kTrajectoryPrompt);
  Expect(!prompt.empty(), "trajectory prompt tokenization");

  auto session = model->CreateSession(512, &error);
  Expect(session != nullptr, error);
  Expect(session->Sync(prompt, &error), error);

  int top1_matches = 0;
  std::uint64_t rank_sum = 0;
  int worst_rank = 0;
  gufo::crypto::Sha256Hasher fingerprint;
  for (const int expected_token : kPinnedDs4Trajectory) {
    const auto logits = session->CopyLogits(&error);
    Expect(!logits.empty(), error);
    fingerprint.Update({reinterpret_cast<const std::uint8_t*>(logits.data()),
                        logits.size() * sizeof(float)});
    Expect(expected_token >= 0 &&
               static_cast<std::size_t>(expected_token) < logits.size(),
           "trajectory token range");

    const int selected_token = session->SelectNext(0.0F, nullptr);
    const float expected_logit =
        logits[static_cast<std::size_t>(expected_token)];
    const int rank =
        1 + static_cast<int>(std::count_if(logits.begin(), logits.end(),
                                           [expected_logit](float value) {
                                             return value > expected_logit;
                                           }));
    top1_matches += selected_token == expected_token ? 1 : 0;
    rank_sum += static_cast<std::uint64_t>(rank);
    worst_rank = std::max(worst_rank, rank);

    Expect(session->Evaluate(expected_token, &error), error);
  }

  std::cout << "Pinned DS4 trajectory: top1=" << top1_matches
            << "/128 rank_sum=" << rank_sum << " worst_rank=" << worst_rank
            << " logits_sha256=" << fingerprint.FinishHex() << '\n';
  Expect(top1_matches >= 116, "128-token top-1 agreement");
  Expect(rank_sum <= 142, "128-token aggregate rank");
  Expect(worst_rank <= 3, "128-token worst rank");
}

void CheckSessionBounds(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  std::string error;
  auto session = model->CreateSession(32, &error);
  Expect(session != nullptr, error);
  Expect(session->PrefillCapacity() > 0 && session->PrefillCapacity() <= 32,
         "prefill allocation fits the session context");
  Expect(session->SelectNext(0.0F, nullptr) == -1 &&
             session->CopyLogits(&error).empty(),
         "uninitialized checkpoint cannot expose logits");
  Expect(!session->Evaluate(1, &error),
         "decode requires initialized target state");
  if (model->HasDspark()) {
    std::vector<int> emitted;
    Expect(!session->DsparkStep(&emitted, &error),
           "DSpark requires initialized target state");
  }
  auto prompt = model->Tokenize(kTrajectoryPrompt);
  prompt.resize(30);
  Expect(session->Sync(prompt, &error), error);
  const auto logits = session->CopyLogits(&error);
  auto invalid = prompt;
  invalid[0] = -1;
  Expect(!session->Sync(invalid, &error) &&
             !session->Evaluate(model->VocabSize(), &error),
         "invalid token IDs are rejected before GPU execution");
  Expect(session->CopyLogits(&error) == logits,
         "argument rejection preserves the valid checkpoint");
  while (session->Position() < session->ContextSize()) {
    Expect(session->Evaluate(session->SelectNext(0.0F, nullptr), &error),
           error.c_str());
  }
  Expect(!session->Evaluate(1, &error) && session->Position() == 32,
         "decode cannot advance past the allocated context");
  if (model->HasDspark()) {
    std::vector<int> emitted;
    Expect(!session->DsparkStep(&emitted, &error) && session->Position() == 32,
           "DSpark fallback cannot overrun a full context");
  }
}

void CheckWidePrefill(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  const auto pattern = model->Tokenize(kTrajectoryPrompt);
  Expect(!pattern.empty(), "wide prefill prompt tokenization");
  std::vector<int> tokens(2048);
  for (std::size_t i = 0; i < tokens.size(); ++i) {
    tokens[i] = pattern[i % pattern.size()];
  }
  const auto run = [&](std::uint32_t context_capacity) {
    std::string error;
    auto session = model->CreateSession(context_capacity, &error);
    Expect(session != nullptr, error);
    Expect(session->Sync(tokens, &error), error);
    std::vector<float> trajectory;
    for (int step = 0; step < 4; ++step) {
      Expect(session->Position() == 2048 + step, "wide prefill frontier");
      const auto logits = session->CopyLogits(&error);
      Expect(!logits.empty(), error);
      Expect(std::all_of(logits.begin(), logits.end(),
                         [](float value) { return std::isfinite(value); }),
             "wide prefill finite logits");
      trajectory.insert(trajectory.end(), logits.begin(), logits.end());
      if (step < 3) {
        Expect(session->Evaluate(session->SelectNext(0.0F, nullptr), &error),
               error.c_str());
      }
    }
    return trajectory;
  };
  const auto reference = run(4096);
  const auto repeat = run(262144);
  Expect(
      reference == repeat,
      "2K prefill and continuation retain exact logits with a 262K capacity");
  const auto* bytes = reinterpret_cast<const std::uint8_t*>(reference.data());
  std::cout << "Wide prefill fingerprint "
            << gufo::crypto::Sha256Hex(
                   std::span(bytes, reference.size() * sizeof(float)))
            << '\n';
}

void CheckBatchedPrefill(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  constexpr int kTrajectoryRepetitions = 2;

  std::string error;
  const auto prompt = model->Tokenize(kTrajectoryPrompt);
  Expect(!prompt.empty(), "prefill prompt tokenization");
  auto tokens = prompt;
  for (int repetition = 0; repetition < kTrajectoryRepetitions; ++repetition) {
    tokens.insert(tokens.end(), kPinnedDs4Trajectory.begin(),
                  kPinnedDs4Trajectory.end());
  }

  auto batched = model->CreateSession(4096, &error);
  Expect(batched != nullptr, error);
  Expect(batched->Sync(tokens, &error), error);
  const auto batched_logits = batched->CopyLogits(&error);
  Expect(!batched_logits.empty(), error);

  auto sequential = model->CreateSession(4096, &error);
  Expect(sequential != nullptr, error);
  Expect(sequential->Sync(prompt, &error), error);
  for (int repetition = 0; repetition < kTrajectoryRepetitions; ++repetition) {
    for (const int token : kPinnedDs4Trajectory) {
      Expect(sequential->Evaluate(token, &error), error);
    }
  }
  const auto sequential_logits = sequential->CopyLogits(&error);
  Expect(sequential_logits.size() == batched_logits.size(),
         "prefill logit shape");

  double squared_error = 0.0;
  double dot = 0.0;
  double batched_norm = 0.0;
  double sequential_norm = 0.0;
  float max_error = 0.0F;
  bool finite = true;
  for (std::size_t index = 0; index < batched_logits.size(); ++index) {
    const float batched_value = batched_logits[index];
    const float sequential_value = sequential_logits[index];
    finite = finite && std::isfinite(batched_value) &&
             std::isfinite(sequential_value);
    const double difference =
        static_cast<double>(batched_value) - sequential_value;
    squared_error += difference * difference;
    dot += static_cast<double>(batched_value) * sequential_value;
    batched_norm += static_cast<double>(batched_value) * batched_value;
    sequential_norm += static_cast<double>(sequential_value) * sequential_value;
    max_error = std::max(max_error, std::abs(batched_value - sequential_value));
  }

  const double rmse =
      std::sqrt(squared_error / static_cast<double>(batched_logits.size()));
  const double denominator = std::sqrt(batched_norm * sequential_norm);
  const double cosine = denominator > std::numeric_limits<double>::min()
                            ? dot / denominator
                            : 0.0;
  const auto batched_top =
      std::max_element(batched_logits.begin(), batched_logits.end());
  const auto sequential_top =
      std::max_element(sequential_logits.begin(), sequential_logits.end());
  const auto batched_top_index = static_cast<std::size_t>(
      std::distance(batched_logits.begin(), batched_top));
  const auto sequential_top_index = static_cast<std::size_t>(
      std::distance(sequential_logits.begin(), sequential_top));
  const float sequential_choice_logit = batched_logits[sequential_top_index];
  const int sequential_choice_rank =
      1 + static_cast<int>(
              std::count_if(batched_logits.begin(), batched_logits.end(),
                            [sequential_choice_logit](float value) {
                              return value > sequential_choice_logit;
                            }));

  std::cout << "Batched prefill (" << tokens.size()
            << " tokens) vs sequential: rmse=" << rmse << " cosine=" << cosine
            << " max_error=" << max_error
            << " top1_match=" << (batched_top_index == sequential_top_index)
            << " sequential_choice_rank=" << sequential_choice_rank << '\n';
  Expect(finite, "prefill finite logits");
  Expect(rmse <= 1.12, "prefill RMSE envelope");
  Expect(cosine >= 0.979, "prefill cosine envelope");
  Expect(max_error <= 5.0F, "prefill maximum error envelope");
  Expect(sequential_choice_rank <= 3, "prefill sequential choice rank");
}

void CheckConversationalPrefill(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  constexpr std::array<std::size_t, 3> kWidths{32, 64, 96};

  std::string error;
  const auto prompt = model->Tokenize(kTrajectoryPrompt);
  Expect(!prompt.empty(), "conversational prefill prompt tokenization");
  for (const std::size_t width : kWidths) {
    auto tokens = prompt;
    for (std::size_t index = 0; tokens.size() < width; ++index) {
      tokens.push_back(
          kPinnedDs4Trajectory[index % kPinnedDs4Trajectory.size()]);
    }

    auto batched = model->CreateSession(512, &error);
    Expect(batched != nullptr, error);
    Expect(batched->Sync(tokens, &error), error);
    const auto batched_logits = batched->CopyLogits(&error);
    Expect(!batched_logits.empty(), error);

    auto sequential = model->CreateSession(512, &error);
    Expect(sequential != nullptr, error);
    const std::vector<int> first_token{tokens.front()};
    Expect(sequential->Sync(first_token, &error), error);
    for (std::size_t index = 1; index < tokens.size(); ++index) {
      Expect(sequential->Evaluate(tokens[index], &error), error);
    }
    const auto sequential_logits = sequential->CopyLogits(&error);
    Expect(sequential_logits.size() == batched_logits.size(),
           "conversational prefill logit shape");

    double squared_error = 0.0;
    double dot = 0.0;
    double batched_norm = 0.0;
    double sequential_norm = 0.0;
    float max_error = 0.0F;
    bool finite = true;
    for (std::size_t index = 0; index < batched_logits.size(); ++index) {
      const float batched_value = batched_logits[index];
      const float sequential_value = sequential_logits[index];
      finite = finite && std::isfinite(batched_value) &&
               std::isfinite(sequential_value);
      const double difference =
          static_cast<double>(batched_value) - sequential_value;
      squared_error += difference * difference;
      dot += static_cast<double>(batched_value) * sequential_value;
      batched_norm += static_cast<double>(batched_value) * batched_value;
      sequential_norm +=
          static_cast<double>(sequential_value) * sequential_value;
      max_error =
          std::max(max_error, std::abs(batched_value - sequential_value));
    }
    const double rmse =
        std::sqrt(squared_error / static_cast<double>(batched_logits.size()));
    const double denominator = std::sqrt(batched_norm * sequential_norm);
    const double cosine = denominator > std::numeric_limits<double>::min()
                              ? dot / denominator
                              : 0.0;
    const auto batched_top =
        std::max_element(batched_logits.begin(), batched_logits.end());
    const auto sequential_top =
        std::max_element(sequential_logits.begin(), sequential_logits.end());
    const auto batched_top_index = static_cast<std::size_t>(
        std::distance(batched_logits.begin(), batched_top));
    const auto sequential_top_index = static_cast<std::size_t>(
        std::distance(sequential_logits.begin(), sequential_top));
    const float sequential_choice_logit = batched_logits[sequential_top_index];
    const int sequential_choice_rank =
        1 + static_cast<int>(
                std::count_if(batched_logits.begin(), batched_logits.end(),
                              [sequential_choice_logit](float value) {
                                return value > sequential_choice_logit;
                              }));

    std::cout << "Conversational prefill (" << width
              << " tokens) vs sequential: rmse=" << rmse << " cosine=" << cosine
              << " max_error=" << max_error
              << " top1_match=" << (batched_top_index == sequential_top_index)
              << " sequential_choice_rank=" << sequential_choice_rank << '\n';
    Expect(finite, "conversational prefill finite logits");
    Expect(rmse <= 1.12, "conversational prefill RMSE envelope");
    Expect(cosine >= 0.979, "conversational prefill cosine envelope");
    Expect(max_error <= 5.0F, "conversational prefill maximum error envelope");
    Expect(sequential_choice_rank <= 3,
           "conversational prefill sequential choice rank");
  }
}

void CheckSessionBatch(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  using gufo::models::deepseek_v4_flash::SessionBatchItem;

  constexpr std::array<std::string_view, 8> kPrompts{
      "Explain virtual memory in one paragraph.",
      "Write a short C++ function that adds two integers.",
      "What causes ocean tides? Answer concisely.",
      "List three practical ways to reduce database query latency.",
      "Describe how a hash table handles collisions.",
      "Give one advantage of immutable data structures.",
      "Why do compilers inline small functions?",
      "Name two ways to reduce network request latency.",
  };
  constexpr std::array<std::size_t, 8> kPromptTokens{
      32, 48, 64, 96, 128, 160, 192, 256,
  };

  std::string error;
  std::array<std::vector<int>, 8> session_prompts;
  std::array<std::unique_ptr<gufo::models::deepseek_v4_flash::Session>, 8>
      batched;
  std::array<std::unique_ptr<gufo::models::deepseek_v4_flash::Session>, 8>
      sequential;
  for (std::size_t index = 0; index < kPrompts.size(); ++index) {
    const auto prompt =
        model->EncodeChat("You are a concise assistant.", kPrompts[index]);
    Expect(!prompt.empty(), "session batch prompt tokenization");
    auto extended_prompt = prompt;
    for (std::size_t token = 0; extended_prompt.size() < kPromptTokens[index];
         ++token) {
      extended_prompt.push_back(
          kPinnedDs4Trajectory[token % kPinnedDs4Trajectory.size()]);
    }
    session_prompts[index] = std::move(extended_prompt);
  }
  const auto reset_sessions = [&] {
    for (std::size_t index = 0; index < kPrompts.size(); ++index) {
      batched[index] = model->CreateSession(512, &error);
      sequential[index] = model->CreateSession(512, &error);
      Expect(batched[index] != nullptr, error);
      Expect(sequential[index] != nullptr, error);
      Expect(batched[index]->Sync(session_prompts[index], &error),
             error.c_str());
      Expect(sequential[index]->Sync(session_prompts[index], &error),
             error.c_str());
      Expect(batched[index]->SelectNext(0.0F, nullptr) ==
                 sequential[index]->SelectNext(0.0F, nullptr),
             "session batch initial greedy token");
    }
  };
  reset_sessions();

  const int position0 = batched[0]->Position();
  const int position1 = batched[1]->Position();
  const int token0 = batched[0]->SelectNext(0.0F, nullptr);
  const int token1 = batched[1]->SelectNext(0.0F, nullptr);
  const auto expect_preflight_rejection =
      [&](std::span<const SessionBatchItem> items, const char* message) {
        Expect(!model->EvaluateBatch(items, &error), message);
        Expect(batched[0]->Position() == position0 &&
                   batched[1]->Position() == position1,
               "session batch preflight preserves positions");
      };

  const std::array<SessionBatchItem, 2> duplicate_items{{
      {.session = batched[0].get(), .token = token0},
      {.session = batched[0].get(), .token = token0},
  }};
  expect_preflight_rejection(duplicate_items,
                             "session batch rejects duplicate sessions");

  const std::array<SessionBatchItem, 2> invalid_token_items{{
      {.session = batched[0].get(), .token = token0},
      {.session = batched[1].get(), .token = model->VocabSize()},
  }};
  expect_preflight_rejection(invalid_token_items,
                             "session batch rejects invalid tokens");

  batched[1]->SetCancellationCheck([] { return true; });
  const std::array<SessionBatchItem, 2> cancelled_items{{
      {.session = batched[0].get(), .token = token0},
      {.session = batched[1].get(), .token = token1},
  }};
  expect_preflight_rejection(cancelled_items,
                             "session batch rejects cancelled sessions");
  batched[1]->SetCancellationCheck({});

  int comparisons = 0;
  int top1_matches = 0;
  double worst_rmse = 0.0;
  double worst_cosine = 1.0;
  float worst_max_error = 0.0F;
  int worst_sequential_choice_rank = 0;
  const auto compare = [&](std::size_t index) {
    const int batched_token = batched[index]->SelectNext(0.0F, nullptr);
    const int sequential_token = sequential[index]->SelectNext(0.0F, nullptr);
    const auto batched_logits = batched[index]->CopyLogits(&error);
    const auto sequential_logits = sequential[index]->CopyLogits(&error);
    Expect(batched_logits.size() == sequential_logits.size(),
           "session batch logit shape");
    double squared_error = 0.0;
    double dot = 0.0;
    double batched_norm = 0.0;
    double sequential_norm = 0.0;
    float max_error = 0.0F;
    bool finite = true;
    for (std::size_t token_index = 0; token_index < batched_logits.size();
         ++token_index) {
      const float batched_value = batched_logits[token_index];
      const float sequential_value = sequential_logits[token_index];
      finite = finite && std::isfinite(batched_value) &&
               std::isfinite(sequential_value);
      const double difference =
          static_cast<double>(batched_value) - sequential_value;
      squared_error += difference * difference;
      dot += static_cast<double>(batched_value) * sequential_value;
      batched_norm += static_cast<double>(batched_value) * batched_value;
      sequential_norm +=
          static_cast<double>(sequential_value) * sequential_value;
      max_error =
          std::max(max_error, std::abs(batched_value - sequential_value));
    }
    const double rmse =
        std::sqrt(squared_error / static_cast<double>(batched_logits.size()));
    const double denominator = std::sqrt(batched_norm * sequential_norm);
    const double cosine = denominator > std::numeric_limits<double>::min()
                              ? dot / denominator
                              : 0.0;
    const float sequential_choice_logit =
        batched_logits[static_cast<std::size_t>(sequential_token)];
    const int sequential_choice_rank =
        1 + static_cast<int>(
                std::count_if(batched_logits.begin(), batched_logits.end(),
                              [sequential_choice_logit](float value) {
                                return value > sequential_choice_logit;
                              }));

    ++comparisons;
    top1_matches += batched_token == sequential_token ? 1 : 0;
    worst_rmse = std::max(worst_rmse, rmse);
    worst_cosine = std::min(worst_cosine, cosine);
    worst_max_error = std::max(worst_max_error, max_error);
    worst_sequential_choice_rank =
        std::max(worst_sequential_choice_rank, sequential_choice_rank);
    if (batched_token != sequential_token || rmse > 0.85 || cosine < 0.99 ||
        max_error > 4.5F || sequential_choice_rank > 3) {
      std::cout << "Session batch quality detail: member=" << index
                << " position=" << batched[index]->Position()
                << " batched=" << batched_token
                << " sequential=" << sequential_token << " rmse=" << rmse
                << " cosine=" << cosine << " max_error=" << max_error
                << " sequential_choice_rank=" << sequential_choice_rank << '\n';
    }
    Expect(finite, "session batch finite logits");
    Expect(rmse <= 0.85, "session batch RMSE envelope");
    Expect(cosine >= 0.99, "session batch cosine envelope");
    Expect(max_error <= 4.5F, "session batch maximum error envelope");
    Expect(sequential_choice_rank <= 3, "session batch sequential choice rank");
  };

  const auto advance = [&](std::span<const std::size_t> members) {
    std::vector<SessionBatchItem> items;
    items.reserve(members.size());
    for (const std::size_t index : members) {
      const int token = sequential[index]->SelectNext(0.0F, nullptr);
      Expect(sequential[index]->Evaluate(token, &error), error);
      items.push_back({.session = batched[index].get(), .token = token});
    }
    Expect(model->EvaluateBatch(items, &error), error);
    for (const std::size_t index : members) {
      Expect(batched[index]->Position() == sequential[index]->Position(),
             "session batch position");
      compare(index);
    }
  };

  constexpr std::array<std::size_t, 6> kAllSix{0, 1, 2, 3, 4, 5};
  advance(kAllSix);
  reset_sessions();

  constexpr std::array<std::size_t, 4> kAll{0, 1, 2, 3};
  for (int step = 0; step < 3; ++step) {
    advance(kAll);
  }

  constexpr std::array<std::size_t, 2> kChangedMembership{0, 2};
  advance(kChangedMembership);

  constexpr std::array<std::size_t, 8> kAllEight{0, 1, 2, 3, 4, 5, 6, 7};
  advance(kAllEight);

  const int token = sequential[0]->SelectNext(0.0F, nullptr);
  Expect(sequential[0]->Evaluate(token, &error), error);
  Expect(batched[0]->Evaluate(token, &error), error);
  compare(0);

  std::cout << "DeepSeek V4 session batch quality: top1=" << top1_matches << '/'
            << comparisons << " worst_rmse=" << worst_rmse
            << " worst_cosine=" << worst_cosine
            << " worst_max_error=" << worst_max_error
            << " worst_sequential_choice_rank=" << worst_sequential_choice_rank
            << '\n';
}

void CheckDsparkPromptSeed(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  std::string error;
  const auto prompt = model->EncodeChat(
      "You are a helpful assistant",
      "The quick brown fox jumps over the lazy dog. Explain why.");
  Expect(!prompt.empty(), "DSpark seed prompt tokenization");

  auto session = model->CreateSession(512, &error);
  Expect(session != nullptr, error);
  Expect(session->Sync(prompt, &error), error);
  auto stats = session->DsparkStatistics();
  Expect(stats.context_tokens >= prompt.size(),
         "DSpark prefill seeds the complete prompt");

  std::vector<int> emitted;
  Expect(session->DsparkStep(&emitted, &error), error);
  Expect(!emitted.empty(), "DSpark first step emitted tokens");
  stats = session->DsparkStatistics();
  Expect(stats.context_tokens >= prompt.size(),
         "first DSpark cycle retains complete prompt coverage");
  Expect(stats.steps == 1, "DSpark drafts on the first generation cycle");
  Expect(stats.anchors == 1, "DSpark records one target-known anchor");
  Expect(stats.support_drafted == 3, "DSpark begins with three support rows");
  Expect(stats.verifier_rows == 4, "DSpark verifies anchor plus support rows");

  auto short_extension = prompt;
  short_extension.push_back(emitted.front());
  short_extension.push_back(session->SelectNext(0.0F, nullptr));
  session.reset();

  auto extended = model->CreateSession(512, &error);
  Expect(extended != nullptr, error);
  Expect(extended->Sync(prompt, &error), error);
  Expect(extended->Sync(short_extension, &error), error);
  Expect(extended->DsparkStatistics().context_tokens == short_extension.size(),
         "short checkpoint extension seeds and extends DSpark context");
  emitted.clear();
  Expect(extended->DsparkStep(&emitted, &error), error);
  Expect(extended->DsparkStatistics().context_tokens >= short_extension.size(),
         "first draft after extension seeds the captured suffix");
  extended.reset();

  // A short output budget still permits a shorter useful draft.
  for (const std::size_t concurrency : {1U, 2U}) {
    std::vector<std::unique_ptr<gufo::models::deepseek_v4_flash::Session>>
        sessions;
    std::vector<std::vector<int>> output(concurrency);
    std::vector<gufo::models::deepseek_v4_flash::SessionDsparkBatchItem> items;
    for (std::size_t i = 0; i < concurrency; ++i) {
      auto member = model->CreateSession(
          static_cast<uint32_t>(prompt.size() + 5), &error);
      Expect(member != nullptr && member->Sync(prompt, &error), error);
      items.push_back({.session = member.get(),
                       .max_tokens = 4,
                       .max_draft_tokens = 7,
                       .emitted = &output[i]});
      sessions.push_back(std::move(member));
    }
    Expect(model->DsparkStepBatch(items, &error), error);
    for (std::size_t i = 0; i < concurrency; ++i) {
      Expect(sessions[i]->DsparkStatistics().steps == 1,
             "short request/context budget still exercises drafting");
      Expect(!output[i].empty() && output[i].size() <= 4,
             "short draft stays within output and context bounds");
    }
  }
}

void CheckDsparkSnapshots(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  using gufo::models::deepseek_v4_flash::Session;
  std::string error;
  const auto pattern = model->Tokenize(kTrajectoryPrompt);
  for (const std::size_t depth : {53U, 4608U, 16384U}) {
    std::vector<int> prompt(depth);
    for (std::size_t i = 0; i < depth; ++i)
      prompt[i] = pattern[i % pattern.size()];
    auto source = model->CreateSession(20480, &error);
    auto fork = model->CreateSession(20480, &error);
    Expect(source != nullptr && fork != nullptr, error);
    Expect(source->Sync(prompt, &error), error);
    // Exercise both a fresh prefix and a controller with acceptance history.
    if (depth == 53) {
      for (int cycle = 0; cycle < 8; ++cycle) {
        std::vector<int> emitted;
        Expect(source->DsparkStep(8, 7, &emitted, &error), error);
      }
    }
    auto snapshot = source->SaveSnapshot(&error);
    Expect(snapshot != nullptr, error);
    Expect(snapshot->SizeBytes() == source->PayloadBytes(),
           "complete snapshot size accounting");
    const auto saved_stats = source->DsparkStatistics();
    const auto saved_logits = source->CopyLogits(&error);
    Expect(fork->RestoreSnapshot(*snapshot, &error), error);
    Expect(fork->DsparkStatistics() == saved_stats &&
               fork->CopyLogits(&error) == saved_logits,
           "snapshot restores exact support statistics and target frontier");
    for (int cycle = 0; cycle < 12; ++cycle) {
      std::vector<int> expected, actual;
      const std::size_t budget = cycle % 3 == 0 ? 2 : 8;
      Expect(source->DsparkStep(budget, 7, &expected, &error), error);
      Expect(fork->DsparkStep(budget, 7, &actual, &error), error);
      Expect(actual == expected &&
                 source->CopyLogits(&error) == fork->CopyLogits(&error) &&
                 source->DsparkStatistics() == fork->DsparkStatistics(),
             "snapshot continuation repeats tokens, logits, and controller "
             "outcomes exactly");
    }
    const auto source_logits = source->CopyLogits(&error);
    Expect(fork->RestoreSnapshot(*snapshot, &error), error);
    fork->BeginRequest();
    Expect(
        fork->DsparkStatistics().steps == 0 &&
            fork->DsparkStatistics().support_drafted == 0 &&
            fork->DsparkStatistics().context_tokens ==
                saved_stats.context_tokens,
        "prefix reuse resets request statistics and retains support coverage");
    std::vector<int> emitted;
    Expect(fork->DsparkStep(4, 7, &emitted, &error), error);
    Expect(fork->DsparkStatistics().steps == 1,
           "restored prefix drafts immediately");
    Expect(source->CopyLogits(&error) == source_logits,
           "snapshot forks own independent caches");

    std::vector<std::uint8_t> bytes(snapshot->SizeBytes());
    Expect(snapshot->CopyTo(bytes), "snapshot export");
    Expect(!fork->RestoreSnapshot(std::span(bytes).first(bytes.size() - 1),
                                  &error),
           "truncated support state is rejected");
    auto corrupt = bytes;
    corrupt[4] = 0;  // unsupported payload version
    Expect(!fork->RestoreSnapshot(corrupt, &error),
           "old snapshot layout is rejected");
    Expect(fork->RestoreSnapshot(bytes, &error), error);
    Expect(fork->DsparkStatistics() == saved_stats &&
               fork->CopyLogits(&error) == saved_logits,
           "valid restore recovers after a rejected snapshot");
    std::cout << "DSpark exact snapshot continuation at depth " << depth
              << '\n';
  }
}

void CheckDsparkScalarQuality(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  using namespace gufo::models::deepseek_v4_flash;
  constexpr std::array<std::string_view, 4> kPrompts{
      "Continue the pattern for twenty more terms and briefly state the rule: "
      "red, blue, blue, red, blue, blue, red,",
      "Return only JSON for a three-day study plan. Each day must contain a "
      "topic, minutes, and one measurable goal.",
      "Write the opening paragraph of a science-fiction story set in a silent "
      "railway station orbiting Jupiter.",
      "请用简洁的中文解释什么是推测解码，以及为什么草稿模型的接受率会影响性能"
      "。",
  };
  struct Scenario {
    std::size_t concurrency;
    std::size_t depth;
  };
  constexpr std::array<Scenario, 8> scenarios{{{1, 0},
                                               {1, 2048},
                                               {1, 4096},
                                               {2, 4096},
                                               {4, 4096},
                                               {6, 4096},
                                               {8, 16384},
                                               {2, 16384}}};
  std::string error;
  const auto pattern = model->Tokenize(kTrajectoryPrompt);
  Expect(!pattern.empty(), "scalar replay prefix tokenization");
  bool quality_ok = true;
  for (const auto [concurrency, depth] : scenarios) {
    int top1 = 0, greedy_matches = 0, compared = 0, rank_sum = 0,
        worst_rank = 0;
    double worst_rmse = 0, worst_cosine = 1;
    float worst_error = 0;
    const auto context = static_cast<std::uint32_t>(depth + 512);
    std::vector<int> prefix(depth);
    for (std::size_t i = 0; i < depth; ++i)
      prefix[i] = pattern[i % pattern.size()];
    std::unique_ptr<SessionSnapshot> snapshot;
    if (depth != 0) {
      auto base = model->CreateSession(context, &error);
      Expect(base && base->Sync(prefix, &error), error);
      snapshot = base->SaveSnapshot(&error);
      Expect(snapshot != nullptr, error);
    }
    const std::size_t groups = concurrency == 1 ? kPrompts.size() : 1;
    const std::size_t budget = concurrency == 1 ? 32 : 16;
    for (std::size_t group = 0; group < groups; ++group) {
      struct Frontier {
        std::vector<int> tokens;
        std::vector<float> logits;
      };
      std::vector<std::unique_ptr<Session>> speculative;
      std::vector<std::vector<Frontier>> frontiers(concurrency);
      std::vector<std::vector<int>> prompts(concurrency);
      std::vector<std::size_t> generated(concurrency);
      std::vector<std::vector<int>> emitted(concurrency);
      const auto make_session = [&](std::size_t member) {
        auto session = model->CreateSession(context, &error);
        Expect(session != nullptr, error);
        if (snapshot)
          Expect(session->RestoreSnapshot(*snapshot, &error), error);
        Expect(session->Sync(prompts[member], &error), error);
        return session;
      };
      for (std::size_t i = 0; i < concurrency; ++i) {
        auto& prompt = prompts[i];
        prompt = prefix;
        const auto suffix =
            model->EncodeChat("", kPrompts[(group + i) % kPrompts.size()]);
        prompt.insert(prompt.end(), suffix.begin(), suffix.end());
        speculative.push_back(make_session(i));
      }
      while (true) {
        std::vector<SessionDsparkBatchItem> items;
        std::vector<std::size_t> active;
        for (std::size_t i = 0; i < concurrency; ++i) {
          if (generated[i] == budget)
            continue;
          active.push_back(i);
          items.push_back({.session = speculative[i].get(),
                           .max_tokens = budget - generated[i],
                           .max_draft_tokens = 7,
                           .emitted = &emitted[i]});
        }
        if (items.empty())
          break;
        Expect(model->DsparkStepBatch(items, &error), error);
        for (const auto member : active) {
          Expect(!emitted[member].empty() &&
                     emitted[member].size() <= budget - generated[member],
                 "scalar replay makes bounded progress");
          generated[member] += emitted[member].size();
          frontiers[member].push_back(
              {emitted[member], speculative[member]->CopyLogits(&error)});
        }
      }
      Expect(std::any_of(speculative.begin(), speculative.end(),
                         [](const auto& session) {
                           return session->DsparkStatistics().support_drafted >
                                  0;
                         }),
             "scalar replay exercises support drafting");
      // Retain every frontier, then release all speculative KV before replay.
      // Peak residency is C sessions, not C speculative + C scalar sessions.
      speculative.clear();
      for (std::size_t member = 0; member < concurrency; ++member) {
        auto sequential = make_session(member);
        std::size_t replayed = 0;
        for (const auto& frontier : frontiers[member]) {
          for (const int token : frontier.tokens) {
            greedy_matches += token == sequential->SelectNext(0.0F, nullptr);
            const auto logits = sequential->CopyLogits(&error);
            Expect(
                token >= 0 && static_cast<std::size_t>(token) < logits.size(),
                "replayed token is in the reference vocabulary");
            const int rank =
                1 + static_cast<int>(std::count_if(
                        logits.begin(), logits.end(),
                        [&](float value) { return value > logits[token]; }));
            top1 += rank == 1;
            ++compared;
            rank_sum += rank;
            worst_rank = std::max(worst_rank, rank);
            Expect(sequential->Evaluate(token, &error), error);
            ++replayed;
          }
          const auto& candidate = frontier.logits;
          const auto reference = sequential->CopyLogits(&error);
          Expect(candidate.size() == reference.size() && !candidate.empty(),
                 "scalar replay frontier logit shape");
          double squared = 0, dot = 0, candidate_norm = 0, reference_norm = 0;
          float frontier_error = 0;
          std::size_t frontier_worst_token = 0;
          for (std::size_t i = 0; i < candidate.size(); ++i) {
            Expect(std::isfinite(candidate[i]) && std::isfinite(reference[i]),
                   "scalar replay finite frontier logits");
            const double delta =
                static_cast<double>(candidate[i]) - reference[i];
            squared += delta * delta;
            dot += static_cast<double>(candidate[i]) * reference[i];
            candidate_norm += static_cast<double>(candidate[i]) * candidate[i];
            reference_norm += static_cast<double>(reference[i]) * reference[i];
            const float difference = std::abs(candidate[i] - reference[i]);
            if (difference > frontier_error) {
              frontier_error = difference;
              frontier_worst_token = i;
            }
            worst_error = std::max(worst_error, difference);
          }
          if (frontier_error != 0.0F) {
            std::cout << "Replay detail C=" << concurrency << " depth=" << depth
                      << " member=" << member << " generated=" << replayed
                      << " error_token=" << frontier_worst_token
                      << " candidate=" << candidate[frontier_worst_token]
                      << " reference=" << reference[frontier_worst_token]
                      << " rmse=" << std::sqrt(squared / candidate.size())
                      << std::endl;
          }
          worst_rmse =
              std::max(worst_rmse, std::sqrt(squared / candidate.size()));
          worst_cosine = std::min(
              worst_cosine, dot / std::sqrt(candidate_norm * reference_norm));
        }
        Expect(replayed == budget, "scalar replay checks the complete budget");
      }
    }
    std::cout << "DSpark scalar replay C" << concurrency << " depth=" << depth
              << ": top1=" << top1 << '/' << compared
              << " rank_sum=" << rank_sum << " worst_rank=" << worst_rank
              << " rmse=" << worst_rmse << " cosine=" << worst_cosine
              << " max_error=" << worst_error << '\n';
    // Verification now preserves scalar arithmetic. Keep that stronger
    // contract, including the scalar sampler's tie-breaking rule.
    const bool token_quality = greedy_matches == compared;
    const bool logit_quality = worst_error == 0.0F;
    quality_ok = quality_ok && token_quality && logit_quality;
    if (!token_quality || !logit_quality)
      std::cout << "Replay gate C=" << concurrency << " depth=" << depth
                << " token_quality=" << token_quality
                << " logit_quality=" << logit_quality << std::endl;
  }
  Expect(quality_ok,
         "every scalar replay scenario matches scalar tokens and logits");
}

void CheckConcurrentPolicySnapshot(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  using namespace gufo::models::deepseek_v4_flash;
  for (const std::size_t concurrency : {2u, 8u}) {
    std::string error;
    std::vector<std::unique_ptr<Session>> sessions(concurrency);
    std::vector<std::unique_ptr<SessionSnapshot>> snapshots(concurrency);
    std::vector<std::vector<int>> emitted(concurrency);
    std::vector<SessionDsparkBatchItem> items(concurrency);
    for (std::size_t i = 0; i < concurrency; ++i) {
      sessions[i] = model->CreateSession(512, &error);
      Expect(sessions[i] != nullptr, error);
      auto prompt = model->Tokenize(kTrajectoryPrompt);
      Expect(sessions[i]->Sync(prompt, &error), error);
      items[i] = {.session = sessions[i].get(),
                  .max_tokens = 8,
                  .max_draft_tokens = 7,
                  .emitted = &emitted[i]};
    }
    // C2 snapshots a partial four-cycle window; C8 snapshots a cohort whose
    // short-context verification cost cannot be repaid even at full acceptance.
    for (int cycle = 0; cycle < (concurrency == 2 ? 6 : 3); ++cycle)
      Expect(model->DsparkStepBatch(items, &error), error);
    for (std::size_t i = 0; i < concurrency; ++i) {
      snapshots[i] = sessions[i]->SaveSnapshot(&error);
      Expect(snapshots[i] != nullptr, error);
    }
    struct Observation {
      std::vector<int> tokens;
      std::vector<float> logits;
      Session::DsparkStats stats;
      bool operator==(const Observation&) const = default;
    };
    const auto continue_requests = [&] {
      std::vector<Observation> observations;
      for (int cycle = 0; cycle < 8; ++cycle) {
        Expect(model->DsparkStepBatch(items, &error), error);
        for (std::size_t i = 0; i < concurrency; ++i)
          observations.push_back({emitted[i], sessions[i]->CopyLogits(&error),
                                  sessions[i]->DsparkStatistics()});
      }
      return observations;
    };
    const auto expected = continue_requests();
    if (concurrency == 8) {
      Expect(std::all_of(sessions.begin(), sessions.end(),
                         [](const auto& session) {
                           const auto stats = session->DsparkStatistics();
                           return stats.skipped > 0 && stats.steps == 0;
                         }),
             "known unprofitable cycles skip without paying for a probe");
    }
    for (std::size_t i = 0; i < concurrency; ++i)
      Expect(sessions[i]->RestoreSnapshot(*snapshots[i], &error), error);
    Expect(continue_requests() == expected,
           "snapshot retains the partial concurrent cost window and exact "
           "backoff continuation");
    const auto before_single = sessions[0]->DsparkStatistics();
    Expect(sessions[0]->DsparkStep(8, 7, &emitted[0], &error), error);
    const auto after_single = sessions[0]->DsparkStatistics();
    Expect(after_single.steps == before_single.steps + 1 &&
               after_single.skipped == before_single.skipped,
           "returning to C1 immediately resumes drafting after concurrent "
           "backoff");
    std::cout << "DSpark concurrent controller snapshot C" << concurrency
              << ": exact window/backoff continuation\n";
  }
}

void CheckDsparkChangingMembership(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  using gufo::models::deepseek_v4_flash::Session;
  using gufo::models::deepseek_v4_flash::SessionDsparkBatchItem;
  struct Observation {
    std::vector<int> emitted;
    std::vector<float> logits;
    Session::DsparkStats stats;
    int position;
    bool operator==(const Observation&) const = default;
  };
  const auto run = [&] {
    std::string error;
    std::array<std::unique_ptr<Session>, 4> sessions;
    for (std::size_t i = 0; i < sessions.size(); ++i) {
      // Grow shared scratch while older sessions remain live. Their borrowed
      // buffers must survive; the repeat can reuse the largest cached arena.
      sessions[i] = model->CreateSession(512 + 256 * i, &error);
      Expect(sessions[i] != nullptr, error);
      auto prompt = model->Tokenize(kTrajectoryPrompt);
      while (prompt.size() < 120 + i)
        prompt.push_back(kPinnedDs4Trajectory[prompt.size() % 128]);
      Expect(sessions[i]->Sync(prompt, &error), error);
    }
    std::vector<Observation> observations;
    constexpr std::array<std::size_t, 8> widths{1, 2, 4, 3, 1, 4, 2, 4};
    for (std::size_t cycle = 0; cycle < widths.size(); ++cycle) {
      std::array<std::vector<int>, 4> emitted;
      std::array<int, 4> positions;
      for (std::size_t i = 0; i < sessions.size(); ++i)
        positions[i] = sessions[i]->Position();
      std::vector<SessionDsparkBatchItem> items;
      for (std::size_t slot = 0; slot < widths[cycle]; ++slot) {
        const std::size_t index = (slot + cycle) % sessions.size();
        // A one-token member must not force its eligible peers to draft
        // serially.
        const std::size_t budget = widths[cycle] > 2 && slot == 0 ? 1 : 4;
        items.push_back({.session = sessions[index].get(),
                         .max_tokens = budget,
                         .max_draft_tokens = 7,
                         .emitted = &emitted[index]});
      }
      Expect(model->DsparkStepBatch(items, &error), error);
      for (std::size_t i = 0; i < sessions.size(); ++i) {
        Expect(sessions[i]->Position() ==
                   positions[i] + static_cast<int>(emitted[i].size()),
               "changing membership advances only the selected sessions");
        observations.push_back(
            {std::move(emitted[i]), sessions[i]->CopyLogits(&error),
             sessions[i]->DsparkStatistics(), sessions[i]->Position()});
      }
    }
    return observations;
  };
  const auto first = run();
  const auto repeat = run();
  for (std::size_t i = 0; i < first.size(); ++i) {
    if (first[i] != repeat[i]) {
      std::cerr << "Changing membership mismatch cycle=" << i / 4
                << " member=" << i % 4
                << " tokens_equal=" << (first[i].emitted == repeat[i].emitted)
                << " logits_equal=" << (first[i].logits == repeat[i].logits)
                << " stats_equal=" << (first[i].stats == repeat[i].stats)
                << " positions=" << first[i].position << '/'
                << repeat[i].position << '\n';
      break;
    }
  }
  Expect(first == repeat,
         "changing concurrency repeats exact tokens, logits, and state");
  std::cout << "DSpark changing membership C1/C2/C4/C3: exact repeated "
               "continuation\n";
}

void CheckDsparkReproducibility(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  using gufo::models::deepseek_v4_flash::Session;
  using gufo::models::deepseek_v4_flash::SessionDsparkBatchItem;

  constexpr std::array<std::string_view, 4> kPrompts{
      "Continue the pattern: red, blue, blue, red, blue, blue, red,",
      "Return only JSON for a three-day study plan with topic and minutes.",
      "Explain why virtual memory is useful for a database engine.",
      "Write a concise C++20 fixed-capacity ring buffer implementation.",
  };
  constexpr std::size_t kCycles = 6;
  struct Observation {
    std::vector<int> tokens;
    std::vector<float> logits;
    Session::DsparkStats stats;
    int position;
  };

  std::string error;
  for (const std::uint32_t tail : {1U, 3U, 7U}) {
    auto configured = model->CreateSession(512, &error);
    auto legacy = model->CreateSession(512, &error);
    Expect(configured != nullptr && legacy != nullptr, error);
    const auto prompt = model->Tokenize(kPrompts[0]);
    Expect(configured->Sync(prompt, &error), error);
    Expect(legacy->Sync(prompt, &error), error);
    for (int cycle = 0; cycle < 4; ++cycle) {
      const auto before = configured->DsparkStatistics();
      std::vector<int> emitted;
      const SessionDsparkBatchItem item{
          .session = configured.get(),
          .max_tokens = 16,
          .max_draft_tokens = tail,
          .emitted = &emitted,
      };
      Expect(model->DsparkStepBatch(
                 std::span<const SessionDsparkBatchItem>(&item, 1), &error),
             error.c_str());
      const auto after = configured->DsparkStatistics();
      Expect(after.support_drafted - before.support_drafted <= tail,
             "single-request draft limit is honored");
      Expect(!emitted.empty() && emitted.size() <= tail + 1,
             "single-request emitted prefix respects its limit");
      {
        std::vector<int> legacy_emitted;
        Expect(legacy->DsparkStep(16, tail, &legacy_emitted, &error),
               error.c_str());
        Expect(emitted == legacy_emitted &&
                   configured->CopyLogits(&error) == legacy->CopyLogits(&error),
               "C1 session and batch APIs retain identical tokens and logits");
      }
    }
    Expect(configured->DsparkStatistics().support_drafted > 0,
           "single-request limit check exercised proposals");
  }
  for (const std::size_t concurrency : {1U, 2U, 4U, 6U, 8U}) {
    auto run = [&] {
      std::vector<std::unique_ptr<Session>> sessions;
      for (std::size_t i = 0; i < concurrency; ++i) {
        auto session = model->CreateSession(512, &error);
        Expect(session != nullptr, error);
        auto prompt = model->Tokenize(kPrompts[i % kPrompts.size()]);
        Expect(!prompt.empty(), "DSpark repeat prompt tokenization");
        if (i >= kPrompts.size()) {
          // Cross the ratio-128 compression boundary at different offsets.
          auto context = model->Tokenize(kTrajectoryPrompt);
          context.insert(context.end(), kPinnedDs4Trajectory.begin(),
                         kPinnedDs4Trajectory.end());
          context.resize(120 + i - prompt.size());
          context.insert(context.end(), prompt.begin(), prompt.end());
          prompt = std::move(context);
        }
        Expect(session->Sync(prompt, &error), error);
        sessions.push_back(std::move(session));
      }

      std::vector<Observation> observations;
      for (std::size_t cycle = 0; cycle < kCycles; ++cycle) {
        std::vector<std::vector<int>> emitted(concurrency);
        std::vector<SessionDsparkBatchItem> items;
        for (std::size_t slot = 0; slot < concurrency; ++slot) {
          // Rotate request order and vary budgets to exercise ragged rows,
          // rejection/rollback, and the one-token tail of a request.
          const std::size_t index = (slot + cycle) % concurrency;
          const std::size_t budget = cycle == 0 ? 7 : 1 + (index + cycle) % 5;
          items.push_back({.session = sessions[index].get(),
                           .max_tokens = budget,
                           .max_draft_tokens = 7,
                           .emitted = &emitted[index]});
        }
        Expect(model->DsparkStepBatch(items, &error), error);
        for (std::size_t i = 0; i < concurrency; ++i) {
          const auto logits = sessions[i]->CopyLogits(&error);
          Expect(!logits.empty(), error);
          Expect(std::all_of(logits.begin(), logits.end(),
                             [](float value) { return std::isfinite(value); }),
                 "finite concurrent DSpark frontier logits");
          Expect(!emitted[i].empty(), "each DSpark request makes progress");
          const std::size_t budget = cycle == 0 ? 7 : 1 + (i + cycle) % 5;
          Expect(emitted[i].size() <= budget, "DSpark respects request budget");
          observations.push_back({std::move(emitted[i]), logits,
                                  sessions[i]->DsparkStatistics(),
                                  sessions[i]->Position()});
        }
      }
      return observations;
    };

    const auto reference = run();
    const auto candidate = run();
    std::vector<std::uint8_t> fingerprint;
    const auto append = [&](const auto& values) {
      const auto* bytes = reinterpret_cast<const std::uint8_t*>(values.data());
      fingerprint.insert(fingerprint.end(), bytes,
                         bytes + values.size() * sizeof(values[0]));
    };
    for (const auto& observation : candidate) {
      append(observation.tokens);
      append(observation.logits);
      append(std::array<std::uint64_t, 4>{
          static_cast<std::uint64_t>(observation.position),
          observation.stats.support_drafted, observation.stats.support_accepted,
          observation.stats.verifier_rows});
    }
    std::cout << "DSpark fingerprint C" << concurrency << " "
              << gufo::crypto::Sha256Hex(fingerprint) << '\n';
    Expect(reference.size() == candidate.size(), "same observation count");
    std::uint64_t drafted = 0;
    for (std::size_t i = 0; i < reference.size(); ++i) {
      const auto& a = reference[i];
      const auto& b = candidate[i];
      if (a.tokens != b.tokens || a.logits != b.logits) {
        double square_error = 0;
        float max_error = 0;
        std::size_t mismatched_logits = 0;
        for (std::size_t j = 0; j < a.logits.size(); ++j) {
          const float delta = a.logits[j] - b.logits[j];
          square_error += static_cast<double>(delta) * delta;
          max_error = std::max(max_error, std::abs(delta));
          mismatched_logits += a.logits[j] != b.logits[j];
        }
        std::cerr << "DSpark repeat route mismatch C=" << concurrency
                  << " cycle=" << i / concurrency
                  << " request=" << i % concurrency
                  << " logits=" << mismatched_logits
                  << " rmse=" << std::sqrt(square_error / a.logits.size())
                  << " max=" << max_error
                  << " drafted=" << a.stats.support_drafted << "/"
                  << b.stats.support_drafted
                  << " accepted=" << a.stats.support_accepted << "/"
                  << b.stats.support_accepted
                  << " verifier=" << a.stats.verifier_rows << "/"
                  << b.stats.verifier_rows << " position=" << a.position << "/"
                  << b.position << "\ntokens:";
        for (const int token : a.tokens)
          std::cerr << ' ' << token;
        std::cerr << "\ncandidate:";
        for (const int token : b.tokens)
          std::cerr << ' ' << token;
        std::cerr << '\n';
      }
      Expect(a.tokens == b.tokens,
             "DSpark repeat retains exact emitted tokens");
      Expect(a.logits == b.logits,
             "DSpark repeat retains full frontier logits");
      Expect(a.position == b.position,
             "DSpark repeat retains request position");
      Expect(
          a.stats.verifier_rows == b.stats.verifier_rows &&
              a.stats.verifier_accepted == b.stats.verifier_accepted &&
              a.stats.support_drafted == b.stats.support_drafted &&
              a.stats.support_accepted == b.stats.support_accepted &&
              a.stats.positional_accepted == b.stats.positional_accepted &&
              a.stats.anchors == b.stats.anchors &&
              a.stats.full_blocks == b.stats.full_blocks &&
              a.stats.steps == b.stats.steps &&
              a.stats.skipped == b.stats.skipped &&
              a.stats.context_tokens == b.stats.context_tokens,
          "DSpark repeat retains all speculative counters and support state");
      if (i >= reference.size() - concurrency) {
        drafted += b.stats.support_drafted;
      }
    }
    if (concurrency == 8) {
      Expect(drafted == 0 &&
                 std::all_of(candidate.end() - concurrency, candidate.end(),
                             [](const auto& observation) {
                               return observation.stats.steps == 0 &&
                                      observation.stats.skipped > 0;
                             }),
             "short-context C8 repeats without unprofitable probes");
    } else {
      Expect(drafted > 0,
             "DSpark repeat comparison exercised DSpark proposals");
    }
    std::cout << "DSpark repeat C" << concurrency << ": " << reference.size()
              << " exact token/logit/state comparisons, drafted=" << drafted
              << '\n';
  }
}

}  // namespace

int main(int argc, char** argv) try {
  std::cout << std::unitbuf;
  const char* model_path = std::getenv("GUFO_DEEPSEEK_V4_FLASH_MODEL");
  if (model_path == nullptr || model_path[0] == '\0') {
    std::cout << "SKIP: GUFO_DEEPSEEK_V4_FLASH_MODEL is not set\n";
    return 77;
  }

  using gufo::models::deepseek_v4_flash::Model;
  using gufo::models::deepseek_v4_flash::ModelOptions;

  const bool dspark_replay =
      argc == 2 && std::string_view(argv[1]) == "--dspark-replay";
  const bool dspark =
      dspark_replay || (argc == 2 && std::string_view(argv[1]) == "--dspark");
  const bool wide_prefill =
      argc == 2 && std::string_view(argv[1]) == "--wide-prefill";
  const bool official = argc == 3 && std::string_view(argv[1]) == "--official";
  const bool prefill_only =
      argc == 4 && std::string_view(argv[3]) == "--prefill-only";
  const bool frontiers = (argc == 3 || prefill_only) &&
                         std::string_view(argv[1]) == "--reference-frontiers";
  if (argc > 1 && !dspark && !wide_prefill && !official && !frontiers) {
    std::cerr << "usage: ds4_quality_test "
                 "[--dspark|--dspark-replay|--wide-prefill|--official OUT.json|"
                 "--reference-frontiers OUT-DIR [--prefill-only]]\n";
    return 2;
  }
  const char* dspark_model_path =
      dspark ? std::getenv("GUFO_DEEPSEEK_V4_FLASH_DSPARK_MODEL") : nullptr;
  if (dspark && (dspark_model_path == nullptr || *dspark_model_path == '\0')) {
    std::cout << "SKIP: GUFO_DEEPSEEK_V4_FLASH_DSPARK_MODEL is not set\n";
    return 77;
  }
  std::string error;
  const auto model =
      Model::Load(model_path,
                  ModelOptions{
                      .max_context = 262144,
                      .dspark_model_path =
                          dspark_model_path != nullptr ? dspark_model_path : "",
                  },
                  &error);
  Expect(model != nullptr, error);
  Expect(model->VocabSize() > 0, "vocabulary size");
  Expect(!model->ModelName().empty(), "model name");

  if (official) {
    gufo::testing::ds4::ScoreOfficialReference(model, argv[2]);
    return 0;
  }
  if (frontiers) {
    gufo::testing::ds4::DumpReferenceFrontiers(model, argv[2], prefill_only);
    return 0;
  }
  if (wide_prefill) {
    CheckWidePrefill(model);
    return 0;
  }
  if (dspark_replay) {
    CheckDsparkScalarQuality(model);
    return 0;
  }
  if (dspark) {
    CheckDsparkReproducibility(model);
    CheckDsparkChangingMembership(model);
    CheckConcurrentPolicySnapshot(model);
    CheckDsparkScalarQuality(model);
    CheckDsparkPromptSeed(model);
    CheckDsparkSnapshots(model);
    CheckSessionBounds(model);
    return 0;
  }

  gufo::testing::ds4::CheckTokenGoldens(*model);
  const auto prompt =
      model->EncodeChat("You are a concise assistant.", "Reply with one word.");
  Expect(!prompt.empty(), "chat prompt tokenization");

  auto session = model->CreateSession(4096, &error);
  Expect(session != nullptr, error);
  Expect(session->Sync(prompt, &error), error);
  Expect(session->Position() == static_cast<int>(prompt.size()),
         "prefill position");

  const auto logits = session->CopyLogits(&error);
  Expect(!logits.empty(), error);
  Expect(std::all_of(logits.begin(), logits.end(),
                     [](float value) { return std::isfinite(value); }),
         "finite logits");

  const int checkpoint_position = session->Position();
  const int first_token = session->SelectNext(0.0F, nullptr);
  Expect(first_token >= 0, "first greedy token");
  Expect(!model->DecodeToken(first_token).empty(), "first token text");
  auto snapshot = session->SaveSnapshot(&error);
  Expect(snapshot != nullptr, error);
  Expect(snapshot->SizeBytes() > 0, "snapshot payload");
  Expect(session->Evaluate(first_token, &error), error);

  const int second_token = session->SelectNext(0.0F, nullptr);
  Expect(second_token >= 0, "second greedy token");
  Expect(session->Evaluate(second_token, &error), error);
  Expect(session->Position() == static_cast<int>(prompt.size()) + 2,
         "decode position");

  Expect(session->RestoreSnapshot(*snapshot, &error), error);
  Expect(session->Position() == checkpoint_position, "restored position");
  Expect(session->SelectNext(0.0F, nullptr) == first_token,
         "restored greedy token");
  Expect(session->CopyLogits(&error) == logits, "restored logits");

  CheckPinnedTrajectory(model);
  CheckBatchedPrefill(model);
  CheckConversationalPrefill(model);
  CheckWidePrefill(model);
  if (!model->HasDspark()) {
    CheckSessionBatch(model);
  }
  if (dspark_model_path != nullptr && dspark_model_path[0] != '\0') {
    CheckDsparkPromptSeed(model);
  }

  std::cout << "DeepSeek V4 Flash model/session test passed\n";
  CheckSessionBounds(model);
  return 0;
} catch (const std::exception& error) {
  std::cerr << "FAIL: " << error.what() << '\n';
  return EXIT_FAILURE;
}
