#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

#include "src/models/deepseek_v4_flash/engine.hpp"

namespace {

void Expect(bool condition, const char* message) {
  if (!condition) {
    std::cerr << "FAIL: " << message << '\n';
    std::abort();
  }
}

constexpr std::string_view kTrajectoryPrompt =
    "Continue this technical explanation with concrete examples and "
    "tradeoffs: Virtual memory lets an operating system";

// Generated by antirez/ds4 revision 84cc882352757baf628a1776badf7cc54d584e28.
constexpr std::array<int, 128> kPinnedDs4Trajectory{
    1347,  17491, 305,  11586, 8412,  412,  260,  1840,  6464,  14261, 16,
    983,   18954, 6781, 294,   1192,  1949, 6464, 436,   6623,  343,   458,
    1205,  436,   344,  1505,  362,   11,   5566, 6460,  305,   17491, 11096,
    16,    983,   4491, 6464,  19627, 3510, 304,  6783,  16,    983,   4491,
    270,   1487,  850,  10920, 16,    1890, 436,  28162, 260,   1699,  1347,
    850,   6464,  1099, 344,   22920, 3510, 16,   455,   1840,  41036, 477,
    28,    7294,  469,  850,   4190,  6783, 29,   15842, 4256,  1014,  29,
    305,   3283,  362,  1487,  31489, 3504, 304,  5167,  18585, 4346,  91604,
    16,    983,   588,  990,   1635,  260,  1487, 39376, 16,    983,   6026,
    25454, 1014,  304,  10181, 6464,  16,   983,  6026,  1014,  304,   30376,
    16,    983,   9347, 270,   15599, 294,  270,  20616, 14,    2918,  436,
    2231,  366,   9026, 295,   6464,  9694, 436,
};

void CheckPinnedTrajectory(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  std::string error;
  const auto prompt = model->Tokenize(kTrajectoryPrompt);
  Expect(!prompt.empty(), "trajectory prompt tokenization");

  auto session = model->CreateSession(4096, &error);
  Expect(session != nullptr, error.c_str());
  Expect(session->Sync(prompt, &error), error.c_str());

  int top1_matches = 0;
  std::uint64_t rank_sum = 0;
  int worst_rank = 0;
  for (const int expected_token : kPinnedDs4Trajectory) {
    const auto logits = session->CopyLogits(&error);
    Expect(!logits.empty(), error.c_str());
    Expect(expected_token >= 0 &&
               static_cast<std::size_t>(expected_token) < logits.size(),
           "trajectory token range");

    const int selected_token = session->SelectNext(0.0F, nullptr);
    const float expected_logit =
        logits[static_cast<std::size_t>(expected_token)];
    const int rank =
        1 + static_cast<int>(std::count_if(logits.begin(), logits.end(),
                                           [expected_logit](float value) {
                                             return value > expected_logit;
                                           }));
    top1_matches += selected_token == expected_token ? 1 : 0;
    rank_sum += static_cast<std::uint64_t>(rank);
    worst_rank = std::max(worst_rank, rank);

    Expect(session->Evaluate(expected_token, &error), error.c_str());
  }

  std::cout << "Pinned DS4 trajectory: top1=" << top1_matches
            << "/128 rank_sum=" << rank_sum << " worst_rank=" << worst_rank
            << '\n';
  Expect(top1_matches >= 116, "128-token top-1 agreement");
  Expect(rank_sum <= 142, "128-token aggregate rank");
  Expect(worst_rank <= 3, "128-token worst rank");
}

void CheckBatchedPrefill(
    const std::shared_ptr<gufo::models::deepseek_v4_flash::Model>& model) {
  constexpr int kTrajectoryRepetitions = 2;

  std::string error;
  const auto prompt = model->Tokenize(kTrajectoryPrompt);
  Expect(!prompt.empty(), "prefill prompt tokenization");
  auto tokens = prompt;
  for (int repetition = 0; repetition < kTrajectoryRepetitions; ++repetition) {
    tokens.insert(tokens.end(), kPinnedDs4Trajectory.begin(),
                  kPinnedDs4Trajectory.end());
  }

  auto batched = model->CreateSession(4096, &error);
  Expect(batched != nullptr, error.c_str());
  Expect(batched->Sync(tokens, &error), error.c_str());
  const auto batched_logits = batched->CopyLogits(&error);
  Expect(!batched_logits.empty(), error.c_str());

  auto sequential = model->CreateSession(4096, &error);
  Expect(sequential != nullptr, error.c_str());
  Expect(sequential->Sync(prompt, &error), error.c_str());
  for (int repetition = 0; repetition < kTrajectoryRepetitions; ++repetition) {
    for (const int token : kPinnedDs4Trajectory) {
      Expect(sequential->Evaluate(token, &error), error.c_str());
    }
  }
  const auto sequential_logits = sequential->CopyLogits(&error);
  Expect(sequential_logits.size() == batched_logits.size(),
         "prefill logit shape");

  double squared_error = 0.0;
  double dot = 0.0;
  double batched_norm = 0.0;
  double sequential_norm = 0.0;
  float max_error = 0.0F;
  bool finite = true;
  for (std::size_t index = 0; index < batched_logits.size(); ++index) {
    const float batched_value = batched_logits[index];
    const float sequential_value = sequential_logits[index];
    finite = finite && std::isfinite(batched_value) &&
             std::isfinite(sequential_value);
    const double difference =
        static_cast<double>(batched_value) - sequential_value;
    squared_error += difference * difference;
    dot += static_cast<double>(batched_value) * sequential_value;
    batched_norm += static_cast<double>(batched_value) * batched_value;
    sequential_norm += static_cast<double>(sequential_value) * sequential_value;
    max_error = std::max(max_error, std::abs(batched_value - sequential_value));
  }

  const double rmse =
      std::sqrt(squared_error / static_cast<double>(batched_logits.size()));
  const double denominator = std::sqrt(batched_norm * sequential_norm);
  const double cosine = denominator > std::numeric_limits<double>::min()
                            ? dot / denominator
                            : 0.0;
  const auto batched_top =
      std::max_element(batched_logits.begin(), batched_logits.end());
  const auto sequential_top =
      std::max_element(sequential_logits.begin(), sequential_logits.end());
  const auto batched_top_index = static_cast<std::size_t>(
      std::distance(batched_logits.begin(), batched_top));
  const auto sequential_top_index = static_cast<std::size_t>(
      std::distance(sequential_logits.begin(), sequential_top));
  const float sequential_choice_logit = batched_logits[sequential_top_index];
  const int sequential_choice_rank =
      1 + static_cast<int>(
              std::count_if(batched_logits.begin(), batched_logits.end(),
                            [sequential_choice_logit](float value) {
                              return value > sequential_choice_logit;
                            }));

  std::cout << "Batched prefill (" << tokens.size()
            << " tokens) vs sequential: rmse=" << rmse << " cosine=" << cosine
            << " max_error=" << max_error
            << " top1_match=" << (batched_top_index == sequential_top_index)
            << " sequential_choice_rank=" << sequential_choice_rank << '\n';
  Expect(finite, "prefill finite logits");
  Expect(rmse <= 1.12, "prefill RMSE envelope");
  Expect(cosine >= 0.979, "prefill cosine envelope");
  Expect(max_error <= 5.0F, "prefill maximum error envelope");
  Expect(sequential_choice_rank <= 3, "prefill sequential choice rank");
}

}  // namespace

int main() {
  const char* model_path = std::getenv("GUFO_DEEPSEEK_V4_FLASH_MODEL");
  if (model_path == nullptr || model_path[0] == '\0') {
    std::cout << "SKIP: GUFO_DEEPSEEK_V4_FLASH_MODEL is not set\n";
    return 77;
  }

  using gufo::models::deepseek_v4_flash::Model;
  using gufo::models::deepseek_v4_flash::ModelOptions;

  std::string error;
  const auto model = Model::Load(model_path,
                                 ModelOptions{
                                     .max_context = 4096,
                                     .prefill_chunk = 2048,
                                     .power_percent = 100,
                                 },
                                 &error);
  Expect(model != nullptr, error.c_str());
  Expect(model->VocabSize() > 0, "vocabulary size");
  Expect(!model->ModelName().empty(), "model name");

  const auto prompt =
      model->EncodeChat("You are a concise assistant.", "Reply with one word.");
  Expect(!prompt.empty(), "chat prompt tokenization");

  auto session = model->CreateSession(4096, &error);
  Expect(session != nullptr, error.c_str());
  Expect(session->Sync(prompt, &error), error.c_str());
  Expect(session->Position() == static_cast<int>(prompt.size()),
         "prefill position");

  const auto logits = session->CopyLogits(&error);
  Expect(!logits.empty(), error.c_str());
  Expect(std::all_of(logits.begin(), logits.end(),
                     [](float value) { return std::isfinite(value); }),
         "finite logits");

  const int checkpoint_position = session->Position();
  const int first_token = session->SelectNext(0.0F, nullptr);
  Expect(first_token >= 0, "first greedy token");
  Expect(!model->DecodeToken(first_token).empty(), "first token text");
  auto snapshot = session->SaveSnapshot(&error);
  Expect(snapshot != nullptr, error.c_str());
  Expect(snapshot->SizeBytes() > 0, "snapshot payload");
  Expect(session->Evaluate(first_token, &error), error.c_str());

  const int second_token = session->SelectNext(0.0F, nullptr);
  Expect(second_token >= 0, "second greedy token");
  Expect(session->Evaluate(second_token, &error), error.c_str());
  Expect(session->Position() == static_cast<int>(prompt.size()) + 2,
         "decode position");

  Expect(session->RestoreSnapshot(*snapshot, &error), error.c_str());
  Expect(session->Position() == checkpoint_position, "restored position");
  Expect(session->SelectNext(0.0F, nullptr) == first_token,
         "restored greedy token");
  Expect(session->CopyLogits(&error) == logits, "restored logits");

  CheckPinnedTrajectory(model);
  CheckBatchedPrefill(model);

  std::cout << "DeepSeek V4 Flash model/session test passed\n";
  return 0;
}
